### ISSUE TITLE
Format dates differently

### ISSUE THREAD

**Issue by Natoman95** [gordon-cs/ZB-NG-Senior-Project#106]
Change from 3/15/2018 to March 3, 2018

**Comment by DonutPirate** [comment]
Also, see my comment on the #68 pull request

**Comment by Natoman95** [comment]
I'm open to discussion on this one. I just use issues sometimes to record things I think should be done but they may not all be good ideas.

**Comment by Natoman95** [comment]
Yeah, I don't get why the dates are formatted that way. Looks super busy to me...
