### ISSUE TITLE
Relabel tabs to be more intuitive

### ISSUE THREAD

**Issue by DonutPirate** [gordon-cs/ZB-NG-Senior-Project#44]
"My offers" or "my rides", etc to indicate who is requesting and who is offering on that tab

**Comment by Natoman95** [comment]
<img width="359" alt="screen shot 2018-02-21 at 1 24 21 am" src="https://user-images.githubusercontent.com/16950522/36466025-fdcf9a38-16a5-11e8-936b-f7031cdc4f04.png">

I think this might be more intuitive
