### ISSUE TITLE
Icon file

### ISSUE THREAD

**Issue by DonutPirate** [gordon-cs/ZB-NG-Senior-Project#69]
We need a file for all icon imports that can be imported to other classes

**Comment by Natoman95** [comment]
How would that simplify anything?

**Comment by DonutPirate** [comment]
Could avoid lines and lines of imports across files, and we wouldn't risk having different names for the same icons. Also it would ensure that we use the same icons for everything instead of similar/intuitive ones (gives us a library of sorts to check against).

**Comment by Natoman95** [comment]
It wouldn't avoid lines of imports. You'd still have to import them individually from that single file in whatever other file needs them.
